const vocab = [
  { english: "man", french: "homme" },
  { english: "you (plural)", french: "vous" },
  { english: "time", french: "temps" },
  { english: "him", french: "lui" },
  { english: "wind", french: "vent" },
  { english: "there", french: "là" },
  { english: "without", french: "sans" },
  { english: "under", french: "sous" },
  { english: "we will do", french: "nous ferons" },
  { english: "number", french: "nombre" },
  { english: "you are", french: "tu es" },
  { english: "we had", french: "nous avons eu" },
  { english: "according to", french: "selon" },
  { english: "them", french: "eux" },
  { english: "government", french: "gouvernement" },
  { english: "me", french: "moi" },
  { english: "in", french: "dans" },
  { english: "money", french: "argent" },
  { english: "I do", french: "je fais" },
  { english: "I did", french: "j'ai fait" },
  { english: "on", french: "sur" },
  { english: "us", french: "nous" },
  { english: "early", french: "tôt" },
  { english: "great", french: "grand" },
  { english: "child", french: "enfant" },
  { english: "they go", french: "ils vont" },
  { english: "with", french: "avec" },
  { english: "she", french: "elle" },
  { english: "they will have", french: "ils auront" },
  { english: "next", french: "prochain" },
  { english: "I was", french: "j'étais" },
  { english: "they had", french: "ils avaient" },
  { english: "they are", french: "ils sont" },
  { english: "they will be", french: "ils seront" },
  { english: "I will be", french: "je serai" },
  { english: "big", french: "gros" },
  { english: "from", french: "depuis" },
  { english: "I have", french: "j'ai" },
  { english: "they were", french: "ils étaient" },
  { english: "I go", french: "je vais" },
  { english: "person", french: "personne" },
  { english: "he goes", french: "il va" },
  { english: "we will be", french: "nous serons" },
  { english: "air", french: "air" },
  { english: "door", french: "porte" },
  { english: "song", french: "chanson" },
  { english: "before", french: "avant" },
  { english: "about", french: "à propos de" },
  { english: "always", french: "toujours" },
  { english: "after", french: "après" },
  { english: "also", french: "aussi" },
  { english: "last", french: "dernier" },
  { english: "we go", french: "nous allons" },
  { english: "already", french: "déjà" },
  { english: "then", french: "alors" },
  { english: "small", french: "petit" },
  { english: "problem", french: "problème" },
  { english: "good", french: "bon" },
  { english: "friend", french: "ami" },
  { english: "rain", french: "pluie" },
  { english: "water", french: "eau" },
  { english: "music", french: "musique" },
  { english: "we", french: "nous" },
  { english: "to be", french: "être" },
  { english: "they will do", french: "ils feront" },
  { english: "he is", french: "il est" },
  { english: "we will go", french: "nous irons" },
  { english: "high", french: "haut" },
  { english: "slowly", french: "lentement" },
  { english: "they did", french: "ils ont fait" },
  { english: "we went", french: "nous sommes allés" },
  { english: "story", french: "histoire" },
  { english: "food", french: "nourriture" },
  { english: "to go", french: "aller" },
  { english: "now", french: "maintenant" },
  { english: "you do", french: "vous faites" },
  { english: "we will have", french: "nous aurons" },
  { english: "they went", french: "ils sont allés" },
  { english: "they will go", french: "ils iront" },
  { english: "hand", french: "main" },
  { english: "against", french: "contre" },
  { english: "life", french: "vie" },
  { english: "sky", french: "ciel" },
  { english: "world", french: "monde" },
  { english: "we are", french: "nous sommes" },
  { english: "you are", french: "vous êtes" },
  { english: "too", french: "trop" },
  { english: "old", french: "vieux" },
  { english: "often", french: "souvent" },
  { english: "woman", french: "femme" },
  { english: "street", french: "rue" },
  { english: "they (m)", french: "ils" },
  { english: "I will do", french: "je ferai" },
  { english: "little", french: "petit" },
  { english: "he does", french: "il fait" },
  { english: "health", french: "santé" },
  { english: "you go", french: "tu vas" },
  { english: "towards", french: "vers" },
  { english: "fire", french: "feu" },
  { english: "sometimes", french: "parfois" },
  { english: "group", french: "groupe" },
  { english: "window", french: "fenêtre" },
  { english: "letter", french: "lettre" },
  { english: "wall", french: "mur" },
  { english: "I am", french: "je suis" },
  { english: "you have", french: "vous avez" },
  { english: "here", french: "ici" },
  { english: "I", french: "je" },
  { english: "during", french: "pendant" },
  { english: "movie", french: "film" },
  { english: "we were", french: "nous étions" },
  { english: "very", french: "très" },
  { english: "you have", french: "tu as" },
  { english: "you do", french: "tu fais" },
  { english: "you (singular)", french: "tu" },
  { english: "they do", french: "ils font" },
  { english: "today", french: "aujourd'hui" },
  { english: "never", french: "jamais" },
  { english: "own", french: "propre" },
  { english: "she does", french: "elle fait" },
  { english: "at", french: "chez" },
  { english: "I will have", french: "j'aurai" },
  { english: "we did", french: "nous avons fait" },
  { english: "of", french: "de" },
  { english: "soon", french: "bientôt" },
  { english: "important", french: "important" },
  { english: "different", french: "différent" },
  { english: "snow", french: "neige" },
  { english: "to", french: "à" },
  { english: "young", french: "jeune" },
  { english: "fact", french: "fait" },
  { english: "to do", french: "faire" },
  { english: "day", french: "jour" },
  { english: "they (f)", french: "elles" },
  { english: "they have", french: "ils ont" },
  { english: "company", french: "entreprise" },
  { english: "new", french: "nouveau" },
  { english: "I went", french: "je suis allé" },
  { english: "between", french: "entre" },
  { english: "well", french: "bien" },
  { english: "we do", french: "nous faisons" },
  { english: "sea", french: "mer" },
  { english: "her", french: "elle" },
  { english: "he", french: "il" },
  { english: "family", french: "famille" },
  { english: "night", french: "nuit" },
  { english: "you go", french: "vous allez" },
  { english: "this", french: "ceci" },
  { english: "alone", french: "seul" },
  { english: "to have", french: "avoir" },
  { english: "among", french: "parmi" },
  { english: "he has", french: "il a" },
  { english: "other", french: "autre" },
  { english: "together", french: "ensemble" },
  { english: "floor", french: "sol" },
  { english: "first", french: "premier" },
  { english: "right", french: "droit" },
  { english: "around", french: "autour de" },
  { english: "I will go", french: "j'irai" },
  { english: "part", french: "partie" },
  { english: "long", french: "long" },
  { english: "we have", french: "nous avons" },
  { english: "work", french: "travail" },
  { english: "large", french: "grand" },
  { english: "year", french: "année" },
  { english: "love", french: "amour" },
  { english: "maybe", french: "peut-être" },
  { english: "she is", french: "elle est" },
  { english: "place", french: "lieu" },
  { english: "that", french: "cela" },
  { english: "she has", french: "elle a" },
  { english: "I had", french: "j'ai eu" },
  { english: "quickly", french: "vite" },
  { english: "she goes", french: "elle va" },
  { english: "for", french: "pour" },
];
